const SUBMISSION = {
	LOAD: 'SUBMISSION_LOAD',
	LOAD_SUCCESS: 'SUBMISSION_LOAD_SUCCESS',
	LOAD_FAIL: 'SUBMISSION_LOAD_FAIL'
};



// const SHOW = {
// 	LOAD: "STATS_LOAD",
// 	LOAD_SUCCESS: "STATS_LOAD_SUCCESS",
// 	LOAD_FAIL: "STATS_LOAD_FAIL"
// };

export { SUBMISSION /*, SHOW*/ };
