const SUBMISSION = {
	LOAD: 'SUBMISSION_LOAD',
	LOAD_SUCCESS: 'SUBMISSION_LOAD_SUCCESS',
	LOAD_FAIL: 'SUBMISSION_LOAD_FAIL'
};



const FORMS = {
	FETCH: "FETCH_FORMS",
	FETCH_SUCCESS: "FETCH_FORMS_SUCCESS",
	FETCH_FAIL: "FETCH_FORMS_FAIL"
};

export { SUBMISSION , FORMS };
