const SUBMISSION = {
	LOAD: 'SUBMISSION_LOAD',
	LOAD_SUCCESS: 'SUBMISSION_LOAD_SUCCESS',
	LOAD_FAIL: 'SUBMISSION_LOAD_FAIL'
};

const FORMS = {
	FETCH: "FETCH_FORMS",
	FETCH_SUCCESS: "FETCH_FORMS_SUCCESS",
	FETCH_FAIL: "FETCH_FORMS_FAIL"
};

const TOURNAMENTFORMSUBMISSIONS = {
	FETCH: 'TOURNAMENTFORMSUBMISSIONS_FETCH',
	FETCH_SUCCESS: 'TOURNAMENTFORMSUBMISSIONS_FETCHSUCCES'
};

const TEAMS = {
	FETCH: "FETCH_TEAMS",
	FETCH_SUCCESS: "FETCH_TEAMS_SUCCESS",
	FETCH_FAIL: "FETCH_TEAMS_FAIL"
};

const RESPONSEID = {
	FETCH: "RESPONSEID_FETCH",

};

export { SUBMISSION , FORMS , TOURNAMENTFORMSUBMISSIONS , TEAMS ,RESPONSEID  };
